### ISSUE TITLE
AVSBench_semantic Checkpoint

### ISSUE THREAD

**Issue by Baiiiiiiiiii** [yannqi/COMBO-AVS#6]
Hi,

Thank you for sharing this excellent work. 
Could you please also share the checkpoints of COMBO for AVSBench_semantic?

Thank you!

**Comment by yannqi** [comment]
Hello, 
you can train the COMBO on AVSS on your own.
It would take around ~24 hours for training AVSS in a single A100-40G GPU to get a similar performance in our paper.
Note, we did not perform any specific optimization for our hyperparameters due to the time limition. 
Therefore, you can obtain a better performance through hyperparameter search if you want.
Thank you!

**Comment by Baiiiiiiiiii** [comment]
Hi,

Thank you for your advice and instruction.
I try to train the model on my own. However, I got the FileNotFoundError after running `sh scripts/res_train_avs4.sh`.
It cannot find processed_frames/processed_labels_semantic/audio.pkl files.

Could you tell me the file/folder structure and content in COMBO-AVS/AVS_dataset/AVSBench_semantic?

```
|--AVS_dataset
   |--AVSBench_semantic/
      |-- ?
      |-- ?
```

Thank you!

**Comment by yannqi** [comment]
Hello,

For question (1): 
In order to save training time, we resize the video in advance.

The code is as below: [process_avssimg2fixsize.py](https://github.com/yannqi/COMBO-AVS/blob/main/avs_tools/process_avssimg2fixsize.py)
About the audio.pkl, you should download the corresponding datasets, which contain this file.
The download link is shown below.

For question (2):
We download the AVSBench_semantic dataset from [https://github.com/OpenNLPLab/AVSBench](https://github.com/OpenNLPLab/AVSBench). (You should write an application form to them for this dataset.)
And the folder is as below：
![image](https://github.com/yannqi/COMBO-AVS/assets/51905299/3e1d86fa-fb61-4c63-95c5-a817596fa154)

Thank you!
